version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Apply Terraform changes
          command: terraform apply -auto-approve

  terraform_destroy:
    docker:
      - image: hashicorp/terraform:1.0.2
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Destroy Terraform resources
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - terraform_init
      - terraform_apply:
          requires:
            - terraform_init
      - terraform_destroy:
          requires:
            - terraform_apply
